### ISSUE TITLE
Not recognizing BLE device?

### ISSUE THREAD

**Issue by criticalcypress** [andrewjfreyer/monitor#232]
I have monitor.sh working on a raspberry pi zero w, and it is detecting my phone well.  I'm running it with -r -a.  Now I'd like to also have it recognize my electric bike, which has a VESC that speaks BLE, so this should work.  I got the MAC address and added it to `known_static_addresses` (just like my phone), but it does not seem to be picked up.

My `known_static_addresses` looks like this (obfuscating actual MAC addresses):

    11:11:11:11:11:11 phone
    22:22:22:22:22:22 ebike

When I look at the log that monitor.sh outputs, the ebike is consistenly failed to recognize with confidence 0.  However, what's weird is that when the ebike is off, then I see the following output:

    [CMD-NAME]  22:22:22:22:22:22 ebike  Unknown

But when I turn the ebike on (i.e. it's bluetooth module comes online), I see

    [CMD-NAME]  22:22:22:22:22:22 VESC BLE UART Unknown

Note that `VESC BLE UART` is the name of the BLE device in the electric bike (e.g. when I connect to the ebike with my phone), so somehow monitor.sh must have learned that name.  However, the confidence for ebike stays 0.

What am I doing wrong?

**Comment by andrewjfreyer** [comment]
Quite possibly the bike powers down when its not in use. Can you confirm whether the bike stays online when it's parked?

**Comment by criticalcypress** [comment]
It definitely stays online, I can connect to it via the phone app no problem.  Also, monitor.sh actually never picks up the ebike, it reports confidence 0 even right after the bike is started up.

Thanks a lot for the response, if there is any debugging options I can enable, or commands to run that would help triage the problem, I'd be happy to do so.

**Comment by andrewjfreyer** [comment]
There's a bit of a difference between constantly advertising and being able to connect via an app. It's more power efficient for the bike to *listen* for incoming bluetooth connections from your phone than it is to constantly advertise. 

Regardless, are you able to send a name request to the bike via it's mac? `sudo hcitool name 00:00:00:00:00` ?

**Comment by criticalcypress** [comment]
Ah, I see. The bike does not respond to the `hcitool name` command (but my phone does, just to sanity-check my usage of the tool). `hcitool lescan` does not include the bike either (but actually the phone does not show up either after about 2mins). I'm not sure what any of this means. There is an android app for the bike, which can scan for the bike, and it finds the bike without adding any configuration ahead of time, so it does seem scanning for the bike somehow is possible.

**Comment by andrewjfreyer** [comment]
Here's a brief nontechnical explanation. `hcitool name` is a good test to see if the bike is *primarily* a two-way to-many communication bluetooth device. `hcitool lescan` is a good test to see if the bike is *primarily* a beacon.  

Since your phone is not *primarily* a beacon, I wouldn't expect it to show up in an `lescan` operation. (it *was* showing up, but it's a random address that you probably didn't notice). 

What these results tell me is that your bike is a "to-one" bluetooth device that is only listening for and responding to authenticated communications from your phone specifically, since it has been paired. This is similar to bluetooth speakers or headphones - they are typically configured to only communicate with one device until they're put back into pairing mode. 

When the bike is on, it seems like it does respond to name queries, as you posted above. 

Can you post more logs indicating when you turn the bike on?
