### ISSUE TITLE
Report current state

### ISSUE THREAD

**Issue by kses** [andrewjfreyer/monitor#238]
Hi!

Is there a way except restarting the service to report the current state of tracked devices?

Use case: If Home Assistant is restarted for one reason or another, can I without restarting the entire monitor service just get it to report (again) the status of the devices it is tracking?

**Comment by DubhAd** [comment]
Try the `-x` command line argument to tell the MQTT broker to retain the messages.

**Comment by andrewjfreyer** [comment]
Personally, I didn't find a solution that worked as reliably as restarting monitor nodes on each homeassistant restart. I haven't investigated whether this is still the best case for at least a year, so things may have changed. 

I did not use retained messages because beacons send too many messages. 

For known devices, you can always send a `.../KNOWN DEVICE STATES` request to the various monitor nodes to force them to report states of known devices.
