### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by quattroman** [andrewjfreyer/monitor#245]
Hi,

I am using the command sudo bash monitor.sh -t 0C:F3:EE:0D:8B:BA (the MAC address of my RAD Beacon that is advertising every 1 advert per second) The beacon name is Test Beacon 1.

However when I run this command i get the following error message - warning: unknown trigger mode:

any guidance would be appreciated.

Thanks

Peter

**Comment by airdrummingfool** [comment]
If you run `sudo bash monitor.h -h`, you can see usage details.

Here's what it has to say about `-t`:
```
monitor -t[adr]	scan for known devices only on mqtt trigger messages:
				a $mqtt_topicpath/scan/ARRIVE (defined in MQTT preferences file)
				d $mqtt_topicpath/scan/DEPART (defined in MQTT preferences file)
				r send ARRIVE or DEPART messages to trigger other devices to scan
```

so `-t` is not to subscribe to a specific beacon, but to tell `monitor` to only scan when it is triggered via MQTT: if `a` is included, scan when an arrival message is received; if `d` is included, scan when a departure message is received. `r` causes `monitor` to _send_ trigger messages (for advanced usage).

Since you're looking for the MAC address of a beacon, you can probably use `sudo monitor.sh -b` to continually monitor for beacons. If it's a private beacon, you might need to put the info into the `known_beacon_addresses` file. I recommend reading the [readme](https://github.com/andrewjfreyer/monitor/blob/master/README.md), especially the _Background & Technical Details_ section, for more info.
