### ISSUE TITLE
Send push notification after detecting phone

### ISSUE THREAD

**Issue by vschinazi** [andrewjfreyer/monitor#250]
Dear Andrew

I am fascinated by this project but also admit I am a complete newbie. I was wondering if it would be possible to send a push notification with a question (or link to a survey / google form) to a registered device once this device is detected. I teach environmental psychology and I am setting up my raspberry pi to sense the environment. However, I would really like to get a sense of how people are feeling once they enter a specific area (where the sensor / raspberry pi is located). I have a feeling that this can be accomplished with "Monitor" and I would appreciate your feedback on this. 

Specifically, I was able to set up my Pi to work with "Balense Sense" (https://www.balena.io/blog/build-an-environment-and-air-quality-monitor-with-raspberry-pi/) and now I would like to add "Monitor" on top of that to detect registered phones that enter the area of the Pi (within the Bluetooth range) and send them a push notification with a link to a survey or a series of questions. 

Do you think this is feasible? Would this work with Balena?

Anyone else in this forum, if you are interested in such a project and would like to collaborate please let me know. 

Thank you so much for your help

Victor

**Comment by digimystigi** [comment]
@vschinazi I feel your request is outside the scope of this project.  Monitor can be used to notify another tool, such as Home Assistant, to the presence of new devices.  That other tool can then be used for data-gathering - When phones arrive and what mood the user selects, the environmental quality data received from your Balena project, etc.  Monitor should not be extended for project specific applications; it does its job by sending an MQTT notification out.  MQTT itself is not directly useful for "push notifications" without another tool.

Let us not bloat Monitor.

Your project is definitely an intriguing concept, though.  I encourage you to play around with things to learn "why" they work.  The Balena project is a great starting point because it gives you a working solution from which you can start playing around with micro-controllers and low voltage electronics.  Monitor is also a good project to fiddle with.  Look into what MQTT is and what it isn't.  Push notifications as you are looking to use them will require other tools.  Home Assistant is one that I have used and has a great and helpful community, but other tools are available.  If you've got a spare low-power Android device laying around, "Scrypted" is an easy-to-get-into-tool that can merge data from multiple sources as well.  Regardless of the tool you use to merge the data from the various sources, you'll likely need another tool to start analyzing the data.  There are entire sections of the Internet devoted to data analysis.

**Comment by vschinazi** [comment]
Hi
Thank you for your detailed reply. I will follow your advice.
v.
