### ISSUE TITLE
Mosquitto seg faulting, downgraded needed for now

### ISSUE THREAD

**Issue by samora-j** [andrewjfreyer/monitor#254]
It seems like following this guide (2019-10-07) currently fails at the point of installing (starting) mosquitto.
My workaround is to downgrade;
sudo apt-get install mosquitto=1.6.4-0mosquitto1~stretch1
sudo apt-mark hold mosquitto

/cheers

**Comment by rourke** [comment]
Thanks a lot for posting this here. In my case I ran into another problem when starting `monitor.sh`:

```
pi@raspberrypi:~/monitor $ sudo bash monitor.sh
> starting monitor.sh (v. 0.2.197)...
> error: minimum required mosquitto_sub version 1.5+ not found. please update.
> error: minimum required mosquitto_pub version 1.5+ not found. please update.
```

This is because `mosquitto_pub` and `mosquitto_sub` both returned an error "Illegal instruction". So I figured I had to downgrade `libmosquitto-dev`, `mosquitto-clients`, `libmosquitto1` as well.

Basically you can do this to downgrade mosquitto and all its dependencies:

```
sudo apt-get install libmosquitto-dev=1.6.4-0mosquitto1~stretch1 mosquitto=1.6.4-0mosquitto1~stretch1 mosquitto-clients=1.6.4-0mosquitto1~stretch1 libmosquitto1=1.6.4-0mosquitto1~stretch1
sudo apt-mark hold libmosquitto-dev mosquitto mosquitto-clients libmosquitto1
```
