### ISSUE TITLE
Script stops detecting after couple of hours

### ISSUE THREAD

**Issue by brthrsam** [andrewjfreyer/monitor#257]
Any idea what is wrong with my setup with Pi Zero W and Home Assistant? The script is detecting my Samsung S7 correctly for couple of hours. After a while it stops detecting the phone but the script is still running fine (I get OK when sending “monitor/scan/echo”). Sending arrival scan request from HA goes through to Pi but it still doesn’t find my phone. Even restarting the script by sending “monitor/scan/restart” doesn’t help, I need to reboot the whole Pi (power cycle) before it starts working again. I have also tried reinstalling the whole thing. Below is a part of log messages through ssh. Are there some other logs that I should check?

```
pi@raspberrypi:~/monitor $ sudo bash monitor.sh -u -x -td -V
> starting monitor.sh (v. 0.2.197)...
> removing web request caches
> updating monitor.service
> retaining mqtt status reports
> warning: verbose logging is enabled. this setting is only for informational and debugging purposes
> monitor.service updated with arguments:  -x -td
> preference: minimum time between the same type of scan = 15
> preference: regex filter for flags to accept = .*
> preference: regex filter for flags to reject = NONE
> preference: regex filter for manufacturers to accept = .*
> preference: regex filter for manufacturers to reject = NONE
> preference: maximum sequential arrive scan attempts = 1
> preference: maximum sequential depart scan attempts = 2
> preference: selected HCI device = hci0
> mqtt trigger: monitor/scan/ARRIVE
> mqtt trigger: monitor/scan/DEPART
> 5C:XX:XX:XX:F8:44 confidence topic: monitor/1/sts7 (has not previously connected to hci0)
> log listener pid = 25913
> btle scan pid = 25914
> btle text pid = 25915
> btle listener pid = 25917
> mqtt listener pid = 25920
> packet listener pid = 25922
> beacon database time trigger pid = 25925
[+] 0.2.197 04-11-2019 05:51:52 PM [CMD-INFO]	**** started arrival scan [x1 max rep] **** 
[+] 0.2.197 04-11-2019 05:51:55 PM [CMD-SCAN]	(No. 1) 5C:XX:XX:XX:F8:44 arrival? 
[+] 0.2.197 04-11-2019 05:51:55 PM [CMD-RAND]	[passed filter] data: 6C:XX:XX:XX:98:4D pdu: ADV_IND rssi: -70 dBm flags: 0x1a man: Apple, Inc. delay: 0
[+] 0.2.197 04-11-2019 05:51:56 PM [CMD-RAND]	[passed filter] data: 44:XX:XX:XX:C2:C0 pdu: ADV_IND rssi: -47 dBm flags: 0x06 man: Apple, Inc. delay: 0
[+] 0.2.197 04-11-2019 05:52:00 PM [CMD-MQTT]	monitor/1/sts7
 {
    "id":"5C:XX:XX:XX:F8:44",
    "confidence":"0",
    "name":"STS7",
    "manufacturer":"Samsung Electronics CoLtd",
    "type":"KNOWN_MAC",
    "retained":"true",
    "timestamp":"Mon Nov 04 2019 17:52:00 GMT+0000 (GMT)",
    "version":"0.2.197"
 }
[+] 0.2.197 04-11-2019 05:52:01 PM [CMD-MQTT]	monitor/1/sts7/rssi
[+] 0.2.197 04-11-2019 05:52:01 PM [CMD-INFO]	**** completed arrival scan **** 
[+] 0.2.197 04-11-2019 05:52:01 PM [CMD-NAME]	5C:XX:XX:XX:F8:44 STS7  Samsung Electronics CoLtd
[+] 0.2.197 04-11-2019 05:52:02 PM [CMD-RAND]	[passed filter] data: FB:XX:XX:XX:26:91 pdu: ADV_IND rssi: -53 dBm flags: 0x06 man: Tile, Inc. delay: 0
[+] 0.2.197 04-11-2019 05:53:00 PM [CMD-RAND]	[passed filter] data: 40:XX:XX:XX:71:8D pdu: ADV_SCAN_IND rssi: -67 dBm flags: none man: Google delay: 3
[+] 0.2.197 04-11-2019 05:53:00 PM [CMD-INFO]	**** started arrival scan [x1 max rep] **** 
[+] 0.2.197 04-11-2019 05:53:01 PM [CMD-SCAN]	(No. 1) 5C:XX:XX:XX:F8:44 arrival? 
[+] 0.2.197 04-11-2019 05:53:09 PM [CMD-INFO]	**** completed arrival scan **** 
[+] 0.2.197 04-11-2019 05:53:09 PM [CMD-NAME]	5C:XX:XX:XX:F8:44 STS7  Samsung Electronics CoLtd
[+] 0.2.197 04-11-2019 05:53:29 PM [CMD-RAND]	[passed filter] data: 5B:XX:XX:XX:41:FA pdu: ADV_SCAN_IND rssi: -61 dBm flags: none man: Google delay: 2
[+] 0.2.197 04-11-2019 05:53:29 PM [CMD-INFO]	**** started arrival scan [x1 max rep] **** 
[+] 0.2.197 04-11-2019 05:53:29 PM [CMD-SCAN]	(No. 1) 5C:XX:XX:XX:F8:44 arrival? 
[+] 0.2.197 04-11-2019 05:53:34 PM [CMD-RAND]	[passed filter] data: 70:XX:XX:XX:17:59 pdu: ADV_SCAN_IND rssi: -60 dBm flags: none man: Google delay: 0
[+] 0.2.197 04-11-2019 05:53:37 PM [CMD-INFO]	**** completed arrival scan **** 
[+] 0.2.197 04-11-2019 05:53:37 PM [CMD-NAME]	5C:XX:XX:XX:F8:44 STS7  Samsung Electronics CoLtd
[+] 0.2.197 04-11-2019 05:54:27 PM [CMD-INST]	[pass mqtt] arrive scan requested 
[+] 0.2.197 04-11-2019 05:54:28 PM [CMD-INFO]	**** started arrival scan [x1 max rep] **** 
[+] 0.2.197 04-11-2019 05:54:28 PM [CMD-INST]	[pass mqtt] arrive scan requested 
[+] 0.2.197 04-11-2019 05:54:29 PM [CMD-SCAN]	(No. 1) 5C:XX:XX:XX:F8:44 arrival? 
[+] 0.2.197 04-11-2019 05:54:33 PM [DEL-RAND]	RAND 40:XX:XX:XX:71:8D expired after 66 seconds 
[+] 0.2.197 04-11-2019 05:54:37 PM [CMD-INFO]	**** completed arrival scan **** 
[+] 0.2.197 04-11-2019 05:54:38 PM [CMD-NAME]	5C:XX:XX:XX:F8:44 STS7  Samsung Electronics CoLtd
[+] 0.2.197 04-11-2019 05:55:22 PM [CMD-INST]	[pass mqtt] echo 
[+] 0.2.197 04-11-2019 05:55:24 PM [CMD-INST]	[pass mqtt] echo 
[+] 0.2.197 04-11-2019 05:55:37 PM [CMD-INST]	[pass mqtt] service restart requested 
Terminated
```

**Comment by bg1000** [comment]
I am seeing the same issue.  I will also note that:
1) I had to downgrade mosquitto to get it to run at all per this issue - https://github.com/andrewjfreyer/monitor/issues/254
2) If I request an echo when it's in this state it will echo continuously until I request a restart.

**Comment by dennisdek** [comment]
I have also recently started to see this issue. Monitor has been working flawlessly for months and since about a week I have this same issue. I have done a complete reinstall in a different SD card, but same result. I'm using a RPI 3.
Happy to share logs if that helps (just tell me which ones to get from where)

**Comment by shbatm** [comment]
Seeing the same issue with the monitor service hanging after a while. When I look at `systemctl status monitor` I see that it has spawned several identical processes. Have to actually power cycle the Pi to get it to restart correctly. This is running on 3 other Pis, 2 of which are identical installs, with no issues.

@bg1000 - The echo issue is a known bug that was fixed in the dev channel but has yet to be merged into the master.

**Comment by bg1000** [comment]
> @shbatm  - Thanks for letting me know about the echo issue. Since I didn't have a lot invested, wasn't thrilled to try to debug this much bash script and the original author didn't seem to be responding to issues here or on the home assistant community forum I moved on and found another way to do bluetooth scanning.

**Comment by luebbe** [comment]
@bg1000 could you please let us know your current solution?
I tried to get up and running with monitor, but all these issues keep me from being able to use it.

**Comment by bg1000** [comment]
@luebbe I wrote some Python to replace it.  I have paired the functionality down quite a bit since I am only interested in scanning for a couple of phones (I don't need/want BLE support).  I also don't want any sort of periodic scanning since this seems to cause interference with the ESP based devices I have on the WiFi.  I basically use this as a supplement to pinging the phones since they sometimes drop off the WiFi. If the phone shows up on the WiFi or bluetooth then it is home.  If it shows up on neither then it is not_home.

My App has limited knowledge of the bluetooth devices or their current state.  It simply receives a request to scan via MQTT, performs the scan and replies via MQTT.  The requests are queued so you can send multiple requests without waiting for a reply. Any information needed (phone name, address, etc.) is contained in the request message.  There is no departure or arrival scan. There is just scan.  If it sees the phone confidence is set to 100%.  The request also includes the number of consecutive scans required for away.  If the phone isn't seen and the previous confidence was greater than 0% it reduces the confidence accordingly and puts another request in it's own queue until confidence reaches either 0% or 100%.  I trigger scans based on things like the garage door opening or the phones dropping off the WiFi.  

If this reduced set of functionality would work for you I can make the repository public and add a readme file.   I should also mention that I use appdaemon and trigger my scans that way.  I can provide a couple of examples of that. However, if you do your automations directly in homeassistant or use node red you would have to implement that part. I've had this running on 2 Raspberry pi Zero W's for about 2 weeks without having to reset them.

**Comment by onebyside** [comment]
I'd be interested.
________________________________

**Comment by bg1000** [comment]
OK.  Let me see if I can put a readme together in the next few days.

**Comment by bg1000** [comment]
https://github.com/bg1000/bt_monitor
I put together a readme and an install script.  Tonight I tested the installation instructions and install script on a Raspberry pi 3b+ and a Pi Zero W both of which are running fine.  If you decide to try it and have questions or problems please let me know and I'll do my best to help.

**Comment by shbatm** [comment]
Thanks for sharing. I'll have to check it out. If you use multiple instances, you may be interested in this App Daemon script to manage instances in HA (https://github.com/Odianosen25/Monitor-App/) 

BTW, back on the topic of this issue at hand, I found that the `hcitool rssi` scan command is what was causing my instance to hang for some reason. I unpaired the devices from that Pi and just let it run the regular script and it's been up for several days with no issues. Still don't know what's special about hcitool on this RPi3b compared to the other two that work fine.

**Comment by bg1000** [comment]
@shbatm - Thanks for the link to the App Daemon script.  I'll check it out.

**Comment by andrewjfreyer** [comment]
Sorry for the lag in support, yall. Had a kid this year and hobby projects fall off the map. As for this bug report, mosquitto per #254 did appear to be the problem for most users.
