### ISSUE TITLE
Monitor filling up MQTT broker with thousands of topics in 2 weeks

### ISSUE THREAD

**Issue by rourke** [andrewjfreyer/monitor#260]
I've been running monitor for 2 weeks on 2 different Raspberry Pi's. I just checked my MQTT broker and noticed **3.1k retained topics**:

![image](https://user-images.githubusercontent.com/2820753/68898152-31e26780-072f-11ea-81f5-88155b6c69b8.png)

I'm using bluetooth key trackers so I have enabled `-b` so it reports beacon advertisements. I've also enabled `-x` so when Home Assistant restarts it can take on the correct state. I've already set `PREF_FAIL_FILTER_MANUFACTURER_ARRIVE` to `Apple|Samsung|Google` but needless to say it's not quite working out.

Am I somehow able to either:

1. Only retain the reports from devices in my `known_beacon_addresses` file?
2. Only report devices in my `known_beacon_addresses` file?

Either options will result in a clean MQTT broker database.

**Comment by andrewjfreyer** [comment]
That's likely due to the -x flag, else messages are not retained. Most users do not use the -x flag because of issues like this. Overwriting retained messages at a broker seems, at best, inconsistently implemented. 

```
Am I somehow able to either:

Only retain the reports from devices in my known_beacon_addresses file?
Only report devices in my known_beacon_addresses file?
```

Not at this time, no, because this won't help the problem. For some beacons, you'll see an advertisement every all day every day. At one adv every 90 seconds, for a single becaon: 

```
(1  adv / 1.5 minute ) * (1440 minutes / day) * ( 7 days / week) = 7233 messages / week 
```

Lets say you're home for half the day, and about half of the remaining messages when you're home are exact duplicates: 

```
(7233 messages / week) / (2 occupancy adjustment ) / (2 duplicate correction) = 1808 messages / week 
```

Even conservatively, we'd expect near 2000 messages per week that might be separately retained by the broker. Multiply that number based on the number of beacons that you have. Remove some obviously duplicated messages, and it's easy to see how retained messages can get out of control. 

I'd recommend handling HA restarts differently. I do not recommend retaining beacon messages.
