### ISSUE TITLE
How to tell monitor to set presence to 100%

### ISSUE THREAD

**Issue by balonchiks** [andrewjfreyer/monitor#309]
Hi, i have 2 monitor instances running, one next to front door, the other is in the living room. let's say i am not home and both show 0% confidence of a device being at home. when i open the front door, the arrive scan is triggered, however only monitor at the front door get the signal and is set to 100% and the living room one remains at 0% since it's too far away. How do i manually set the living room monitor instance to 100% knowing that if the one at the entrance is showing 100% means that i am definitely at home? Thanks!

**Comment by digimystigi** [comment]
You don't.  That's not the point of how monitor works or why you would have multiple instances.  Monitor will give the appropriate statistics per node. You will need an outside tool that can collect and process the data from all of the nodes to spit out a single value, such as Home Assistant, Node-Red, a custom python script, or otherwise.

**Comment by balonchiks** [comment]
Ok, thanks for clarification.
