### ISSUE TITLE
With retain to true, beacons stay to 100% if they left while monitor is offline

### ISSUE THREAD

**Issue by RomRider** [andrewjfreyer/monitor#78]
Hi,

If monitor is started with `-x` to retain messages while a beacon is there. Then monitor is stopped for whatever reason (infinite loop or maintenance for example) and while it's stopped, the beacon leaves.
On restart, the beacon will always stay as being considered home.

My idea would be: On restart, consider known beacons from the file `config/known_beacon_addresses` as with a "confidence of 100%" without sending the message to MQTT and decrease it's confidence like you'd do because you're not receiving any advertisement from it.

Let me know if you need some testing.
Cheers

**Comment by andrewjfreyer** [comment]
Try out the beta branch, a similar error report has been addressed in that branch.

**Comment by RomRider** [comment]
I'm using the beta branch 0.1.814

**Comment by Lymkin** [comment]
For me, the "departure scan" never runs.  Only the "arrival scan"

**Comment by andrewjfreyer** [comment]
I misread your original post, apologies. The issue addressed in the beta is related to Home Assistant going offline and not receiving updates from monitor. 

If you have retain set to true, and your monitor instance goes offline, your broker will retain the online status of your beacon. This is expected behavior. 

Monitor could go through the known beacons file as you suggest, but it is not good behavior to presume that a beacon is home. I'll consider how to address this specific use case, but in general, using the retain flag will cause your most recent message to be retained.

**Comment by andrewjfreyer** [comment]
That’s the error on HA’s part that has been addressed for known_devices in the beta. 

Else, you can remove the status message variable from the home assistant sensor configuration.
